### PR TITLE
Add error code for network errors.

### PR DESCRIPTION
**Pull request by mvf4z7**

### CODE REVIEW

**Comment by james2doyle** [comment]
Thanks

**Comment by james2doyle** [comment]
You wouldn't happen to know how to test any of these error code would you?

**Comment by steven10172** [comment]
In chrome if you're in offline mode it'll throw the new error. Before these changes it would just throw a JSON parse error if you set `json: true`

**Comment by mvf4z7** [comment]
I just went into Chrome dev tools and turned the network off and made sure
the errors were being thrown in my code.

As far as a good way to unit test, not sure off the top of my head. Would
have to do some research.

**Comment by steven10172** [comment]
For unit testing you should be able to call abort right after the request is made and it will fire the network error.

**Comment by james2doyle** [comment]
Yeah it would be nice to figure out a way to mock "offline". Then I can write some tests for the error codes.

**Comment by james2doyle** [comment]
Hmmm... calling `.abort()` triggers _"Error: CORS request rejected"_ and not the network error

**Comment by james2doyle** [comment]
Was able to test the "offline" by calling the local `package.json` and then calling `.abort()` at the same time. Manage to do the same with CORS but with a live domain.

See 697f2e0fff64d499d35e6c72b56a6dd4ed021ec2

**Comment by steven10172** [comment]
You could also send a live request to another endpoint that does reply with CORS headers (ex: [google.com)](http://google.com)

**Comment by james2doyle** [comment]
The problem was that calling `.abort()` was triggering different errors depending on if it was for a local URL or a CORS URL.

**Pull request merged**
